name: Neil Kimmett
url: http://www.kimmett.me
description: Occasional ramblings about iOS, software, and other things
markdown: redcarpet
highlighter: rouge
future: false
collections:
  talks:
    output: true
